spring:
  redis:
    database: 0 #Redis数据库索引（默认为0）
    host: 192.168.146.128 #Redis服务器地址
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 #连接池中的最大空闲连接
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        min-idle: 0 #连接池中的最小空闲连接
    port: 6379 #Redis服务器连接端口
    timeout: 1800000 #连接超时时间（毫秒）